=== tesseract4444/data-science/university/computer_science/vorlesung09_datastruct/xml/it4all/01_party_dtd.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT party (gast+)>
<!ATTLIST party datum CDATA #REQUIRED>
<!ELEMENT gast (vorname, nachname, getraenk+)>
<!ELEMENT vorname (#PCDATA)>
<!ELEMENT nachname (#PCDATA)>
<!ELEMENT getraenk (#PCDATA)>
<!ATTLIST gast
      nuechtern (true | false) #REQUIRED
      ledig (true | false) #REQUIRED
>

=== tesseract4444/data-science/university/computer_science/vorlesung09_datastruct/xml/it4all/01_party_xml.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE party SYSTEM "01_party_dtd.dtd">
<party datum='2018-05-03'>
    <gast ledig="true" nuechtern="false">
        <vorname>Hans</vorname>
        <nachname>Pans</nachname>
        <getraenk>Vodka</getraenk>    
    </gast>
    <gast ledig="false" nuechtern="true">
        <vorname>Candy</vorname>
        <nachname>Love</nachname>
        <getraenk>Jaegermeister</getraenk>
        <getraenk>Vodka</getraenk> 
        <getraenk>Rum</getraenk> 
    </gast>
</party>
