=== tesseract4444/data-science/university/computer_science/vorlesung09_datastruct/xml/it4all/02_lecture_dtd.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!-- Alt: <!ELEMENT lecture (lecturer+, date+, student+)>
<!ELEMENT lecturer (name, title)>
<!ELEMENT date (hours)>
<!ATTLIST date weekday (mon | tue | wed | thu | fri | sat | sun) #REQUIRED>
<!ELEMENT student (name, matrikel)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT hours (#PCDATA)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT matrikel (#PCDATA)>
-->


<!ELEMENT lecture (lecturer+, date+, student+)>
<!ELEMENT lecturer (name)>
<!ATTLIST lecturer title CDATA #REQUIRED>
<!ELEMENT date (hours)>
<!ATTLIST date weekday (mon | tue | wed | thu | fri | sat | sun) #REQUIRED>
<!ELEMENT student (name)>
<!ATTLIST student matrikel CDATA #REQUIRED>
<!ELEMENT name (#PCDATA)>
<!ELEMENT hours (#PCDATA)>

=== tesseract4444/data-science/university/computer_science/vorlesung09_datastruct/xml/it4all/02_lecture_xml.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE lecture SYSTEM "02_lecture_dtd.dtd">
<lecture>
    <lecturer  title="Prof. Dr.">
        <name>Hans DÃ¶del</name>
    </lecturer>
    <date weekday = "mon">
        <hours>16.00-18.00</hours>
    </date>
    <date weekday="sat">
        <hours>20.00-22.00</hours>
    </date>
    <student matrikel="4563463453">
        <name>Henrietta Hot</name>
    </student>
    <student matrikel="4634342323">
        <name>Lukas Loser</name>
    </student>
</lecture>
