=== tesseract4444/data-science/university/computer_science/vorlesung09_datastruct/xml/it4all/04_breakfast_dtd.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT breakfast (food+)>
<!ELEMENT food (name, price, description, calories)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT price (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT calories (#PCDATA)>

=== tesseract4444/data-science/university/computer_science/vorlesung09_datastruct/xml/it4all/04_breakfast_xml.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE breakfast SYSTEM "04_breakfast_dtd.dtd">
<breakfast>
    <food>
        <name>Ensalada Mista, Baby!</name>
        <price>25.00 Euro</price>
        <description>Bester Salat der Welt</description>
        <calories>Too much!</calories>
    </food>
    <food>
        <name>Pizza alla Mamma mia</name>
        <price>8.00 Euro</price>
        <description>Beste Pizza der Welt</description>
        <calories>425 kcal</calories>
    </food>
</breakfast>
