=== tesseract4444/data-science/university/computer_science/vorlesung09_datastruct/xml/it4all/05_bibliothek_dtd.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT bibliothek (abteilung+)>
<!ELEMENT abteilung (titel, buch+)>
<!ELEMENT buch (isbn, titel, autor, coautor*, jahr, verlag?, auflage?)>
<!ATTLIST buch id CDATA #REQUIRED>
<!ELEMENT isbn (#PCDATA)>
<!ELEMENT titel (#PCDATA)>
<!ELEMENT autor (#PCDATA)>
<!ELEMENT coautor (#PCDATA)>
<!ELEMENT jahr (#PCDATA)>
<!ELEMENT verlag (#PCDATA)>
<!ELEMENT auflage (#PCDATA)>

<!--  Alt:
<!ELEMENT bibliothek (abteilung+)>
<!ELEMENT abteilung (titel, buch+)>
<!ELEMENT buch (id, isbn, titel, autor, coautor*, verlag?, auflage?, jahr)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT isbn (#PCDATA)>
<!ELEMENT titel (#PCDATA)>
<!ELEMENT autor (#PCDATA)>
<!ELEMENT coautor (#PCDATA)>
<!ELEMENT verlag (#PCDATA)>
<!ELEMENT auflage (#PCDATA)>
<!ELEMENT jahr (#PCDATA)>
-->

=== tesseract4444/data-science/university/computer_science/vorlesung09_datastruct/xml/it4all/05_bibliothek_xml.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE bibliothek SYSTEM "05_bibliothek_dtd.dtd">
<bibliothek>
    <abteilung>
        <titel>Area-51</titel>
        <buch id="1">
            <isbn>5634643535</isbn>
            <titel>Dödelhausen</titel>         
            <autor>Hans Dödel</autor>
            <coautor>Dumm Dödel</coautor>
            <jahr>1978</jahr>
            <verlag>Depporaverlag</verlag>
            <auflage>70. Auflage</auflage>           
        </buch>
        <buch id="2">
            <isbn>34634324434</isbn>
            <titel>Dappenheim</titel>         
            <autor>Erika Edelfrau</autor>
            <jahr>1978</jahr>
            <verlag>Depporaverlag</verlag>         
        </buch>
    </abteilung>
</bibliothek>
